### ISSUE TITLE
TypeError: requestShortener.shorten is not a function

### ISSUE THREAD

**Issue by bradennapier** [webpack-contrib/uglifyjs-webpack-plugin#114]
Getting this when trying to use this plugin:

```
 91% additional asset processing/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:240
          return new Error(`${file} from UglifyJs\n${err.message} [${requestShortener.shorten(original.source)}:${original.line},${original.column}][${file}:${err.line},${err.col}]`);
                                                                                      ^

TypeError: requestShortener.shorten is not a function
    at Function.buildError (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:240:87)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:174:56
    at Array.forEach (<anonymous>)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/index.js:157:21
    at step (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:110:11)
    at done (/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:120:22)
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:125:15
    at /Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/node_modules/uglifyjs-webpack-plugin/node_modules/worker-farm/lib/farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
```

**Comment by evilebottnawi** [comment]
@bradennapier can you create minimum reproducible test repo?

**Comment by kzc** [comment]
```
TypeError: requestShortener.shorten is not a function
    at Function.buildError (uglifyjs-webpack-plugin/dist/index.js:240:87)
```
Wild guess - try to run `uglifyjs-webpack-plugin` on invalid ES6 code.

**Comment by evilebottnawi** [comment]
@kzc good catch, thanks, maybe we can output more friendly error on this, in near future i investigate this

**Comment by liuguanhua** [comment]
升级 uglifyjs-webpack-plugin 即可

**Comment by DDCrow** [comment]
According to @liuguanhua, please upgrade or install uglifyjs-webpack-plugin. It's work for me at least
