### ISSUE TITLE
[0.4.6] `unsafe_Func` is not a supported option

### ISSUE THREAD

**Issue by kmvan** [webpack-contrib/uglifyjs-webpack-plugin#123]
OS: Win10 x64
NPM: 3.10.10
NODE: 6.11.1
"uglifyjs-webpack-plugin": "^0.4.6"

Below config for UglifyJsPlugin:)
```javascript
    new UglifyJsPlugin({
            parallel: {
                cache: true,
            },
            mangle: {
                eval: true,
                toplevel: true,
            },
            output: {
                comments: false,
                ascii_only: true,
                beautify: false,
            },
            ie8: false,
            ecma: 5,
            compress: {
                properties: true,
                unsafe: true,
                unsafe_comps: true,
                unsafe_math: true,
                unsafe_proto: true,
                unsafe_regexp: true,
                unsafe_Func: true, // not works
                dead_code: true,
                unused: true,
                conditionals: true,
                keep_fargs: false,
                drop_console: true,
                drop_debugger: true,
                reduce_vars: true,
                if_return: true,
                evaluate: true,
                booleans: true,
                // typeofs: false,
                loops: true,
                toplevel: true,
                top_retain: true,
                hoist_funs: true,
                hoist_vars: true,
                // inline: true, // not works
                join_vars: true,
                cascade: true,
                collapse_vars: true,
                reduce_vars: true,
                negate_iife: true,
                pure_getters: true,
                // pure_funcs: true, // not works
                // arrows: true, // not works
            },
            sourceMap: false,
        }),
```

Error log:
```
ERROR in app.js from UglifyJs
DefaultsError: `unsafe_Func` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/path/to/node_modules/ugli
fyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:86:23)
    at /path/to/node_modules/uglifyjs-webpack-plugin/dist/index.js:239:80

    at Array.forEach (native)
    at Compilation.<anonymous> (/path/to/node_modules/uglifyjs-webpack-pl
ugin/dist/index.js:54:20)
    at next (/path/to/node_modules/tapable/lib/Tapable.js:204:14)
    at LastCallWebpackPlugin.process (/path/to/node_modules/last-call-web
pack-plugin/index.js:126:12)
    ......
```

Any idea:D 
Thank you.

**Comment by kzc** [comment]
> "uglifyjs-webpack-plugin": "^0.4.6"

Those options do not work in that version. `uglifyjs-webpack-plugin@0.4.6` uses `uglify-js@2` not `uglify-es`.  

Try using `uglifyjs-webpack-plugin@1.0.0-beta`. Note: plugin [options](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#options) have changed.

**Comment by evilebottnawi** [comment]
@kmvan yes, please use `uglifyjs-webpack-plugin@1.0.0-beta.2` instead `0.4.6`, thanks!
