### ISSUE TITLE
"Cannot find module 'uglifyjs-webpack-plugin'" at version 1.1.7

### ISSUE THREAD

**Issue by matthewstrom** [webpack-contrib/uglifyjs-webpack-plugin#218]
The upgrade from `1.1.16` to `1.1.17` has caused the following error when I tried starting the Angular CLI. If I downgrade to 1.1.16 the error goes away.

Given that this is a "Cannot find module" error, perhaps the way the module is exported changed between versions?

```
Cannot find module 'uglifyjs-webpack-plugin'
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<project root>/node_modules/@angular/cli/models/webpack-configs/production.js:13:24)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<project root>/node_modules/@angular/cli/models/webpack-configs/index.js:9:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

Node Version: 8.7.0
OS: MacOS High Sierra

**Comment by aav7fl** [comment]
I just started getting the same message this afternoon..

**Comment by michael-ciniawsky** [comment]
[`v1.1.8`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.1.8) 🎉 
Sry guys it was my mistake during release 😅
