### ISSUE TITLE
Build crashes when using 'parallel' and 'sourceMap' options at the same time.

### ISSUE THREAD

**Issue by dawnmist** [webpack-contrib/uglifyjs-webpack-plugin#219]
uglifyjs-webpack-plugin version: 1.1.6
webpack version: 3.10.0
node-js: 8.9.4

I was trying to use the updated version of uglifyjs-webpack-plugin to be able to add caching and parallel builds to an existing project. I have found that I can either have the build generate sourceMaps OR I can have the parallel option turned on, but if I turn on both options the build crashes with the following error message:
```
Creating an optimized production build...
Starting type checking service...
Using 1 worker with 8912MB memory limit
appServer/www/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at ChildProcess.target._send (internal/child_process.js:675:23)
    at ChildProcess.target.send (internal/child_process.js:586:19)
    at Farm.send (appServer/www/node_modules/worker-farm/lib/farm.js:246:9)
    at Farm.processQueue (appServer/www/node_modules/worker-farm/lib/farm.js:292:12)
    at Farm.addCall (appServer/www/node_modules/worker-farm/lib/farm.js:309:8)
    at Farm.<anonymous> (appServer/www/node_modules/worker-farm/lib/farm.js:35:10)
    at _class.boundWorkers (appServer/www/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
    at enqueue (appServer/www/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at tryCatcher (appServer/www/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (appServer/www/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (appServer/www/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (appServer/www/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (appServer/www/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (appServer/www/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (appServer/www/node_modules/bluebird/js/release/async.js:143:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
We are using typescript with the ts-loader compiling code using cache-loader and thread-loader to help with build times, and splitting the syntax/semantic validation of the ts code out to fork-ts-checker-webpack-plugin in a separate thread to the ts-loader(s). It is then further complicated by using Code Splitting and the CommonsChunkPlugin to extract common async code and vendor packages from the initially created bundles, so there are multiple bundles that then finally get processed by uglify.

Webpack's 'devtool' option is simply set to 'source-map'.

Our options given to uglifyjs-webpack-plugin:
```javascript
new UglifyJsPlugin({
  cache: true,
  // Issue with both parallel and sourceMap being enabled at the same time - build crashes
  parallel: true,
  sourceMap: true,
  uglifyOptions: {
    output: {
      comments: false,
      // Turned on because emoji and regex is not minified properly using default
      // https://github.com/facebookincubator/create-react-app/issues/2488
      ascii_only: true,
    },
    // Compress options: @see https://github.com/mishoo/UglifyJS2 for descriptions
    // For required options: @see:
    //   https://slack.engineering/keep-webpack-fast-a-field-guide-for-better-build-performance-f56a5995e8f1
    compress: {
      booleans: true, // default: true
      collapse_vars: true, // default: true
      // Comparisons disabled because of an issue with Uglify breaking seemingly valid code:
      // https://github.com/facebookincubator/create-react-app/issues/2376
      comparisons: false, // default: true,
      conditionals: true, // default: true, required by create-react-app
      dead_code: true, // default: true, required by create-react-app
      drop_console: false, // default: false
      drop_debugger: true, // default: true
      evaluate: true, // default: true, required by create-react-app
      expression: true, // default: false
      global_defs: {}, // declare values as constants for code removal (if not already marked const in the source)
      hoist_funs: false, // default: false
      hoist_props: false, // default: true
      hoist_vars: false, // default: false
      if_return: true, // default: true
      inline: false, // default: true
      join_vars: true, // default: true
      keep_fargs: true, // default: true
      keep_fnames: false, // default: false
      keep_infinity: false, // default: false
      loops: false, // default: true
      negate_iife: false, // default: true
      passes: 1, // default: 1, number of compression passes.
      properties: false, // default: true
      pure_funcs: null, // default null - array of function names that have no side effects and thus can be dropped
      pure_getters: 'strict', // default 'strict'
      reduce_funcs: false, // default: true
      reduce_vars: false, // default: true
      sequences: true, // default: true
      side_effects: false, // default: true, enables dropping funcs marked as pure
      switches: true, // default: true
      toplevel: true, // default: false
      top_retain: null, // default: null, array of funcs/regex for ones not to drop if unused
      typeofs: false, // default: true - IE10 & below needs this to be false.
      unused: true, // default: true
      warnings: false // default: false
    },
    mangle: true // negligible timing cost + significant code reduction
  }
})
```

Is it a known issue that the parallel and sourceMap options cannot be activated together? Or is it due to generating multiple bundles that all need to be uglified? Or any other ideas? We'd really like to be able to still generate source maps with the parallel build.

**Comment by evilebottnawi** [comment]
@dawnmist What is your os? Also can you create minimum reproducible test repo?

**Comment by dawnmist** [comment]
Os is linux (Ubuntu 16.04 LTS).

I've just spent some time trying to duplicate the issue in a 'new' react project (using react-scripts-ts), and it's working in that repo. That pretty strongly indicates that the issue is due to something else in our config that is interfering.

I'll keep trying to track it down from my end, and will update if I can find the cause.

**Comment by evilebottnawi** [comment]
@dawnmist try to update (`node_modules`, don't forget about to update `package-lock.json`) file first, maybe something buggy in deps

**Comment by dawnmist** [comment]
Deleting the node_modules directory and reinstalling the packages has fixed the issue - some packages came in with updated versions compared to what had been installed previously, so I suspect it was a conflict between something else and uglifyjs-webpack-plugin that was addressed by the update to the other package.
