### ISSUE TITLE
Webpack build failure when using uglifyjs plugin

### ISSUE THREAD

**Issue by Shavindra** [webpack-contrib/uglifyjs-webpack-plugin#228]
When running `webpack` uglifyjs throws following error

`ERROR in app.bundle.js from UglifyJs
TypeError: sym.definition is not a function
    at may_modify (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:8931:31)
    at Object.abort [as before] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:8541:74)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4570:35)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4586:25)
    at doit (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:130:23)
    at MAP (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:156:52)
    at do_list (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4585:16)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4664:28)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4573:17)
    at collapse (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:8617:39)
    at tighten_body (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:8429:17)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:10529:9)
    at AST_Node.eval [as optimize] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7682:23)
    at Object.before (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7665:24)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4570:35)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4739:33)
    at Object.before (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7660:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4570:35)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4586:25)
    at doit (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:130:23)
    at MAP (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:156:52)
    at do_list (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4585:16)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4745:27)
    at Object.before (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:7660:9)
    at AST_Node.eval [as transform] (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4570:35)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4586:25)
    at doit (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:130:23)
    at MAP (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:156:52)
    at do_list (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4585:16)
    at eval (eval at <anonymous> (C:\Dev\TruRating\cloud-core-react-analytics\node_modules\uglifyjs-webpack-plugin\node_modules\uglify-es\tools\node.js:1:0), <anonymous>:4682:25)`

Here is the config 
`        new UglifyJsPlugin({
            uglifyOptions: {
                ie8: false,
                output: {
                    comments: false,
                    beautify: false,
                },
                compress: true,
                warnings: false,
                mangle: {
                    safari10: true,
                }
            }
        }),` 

but it still fails even if just use `new new UglifyJsPlugin()`

**Comment by djyde** [comment]
+1

It seems because https://github.com/mishoo/UglifyJS2/issues/2896

**Comment by skiritsis** [comment]
Facing the same issue as well after updating.

**Comment by evilebottnawi** [comment]
Confirm, investigate. 
**Recomendation: ** please use lock file to avoid this problem!

**Comment by shusiwei** [comment]
+1

**Comment by satazor** [comment]
I've created an issue on the uglify repo, see https://github.com/mishoo/UglifyJS2/issues/2901

**Comment by evilebottnawi** [comment]
@satazor thanks, right now i also created a problem, you were faster :smile:

**Comment by evilebottnawi** [comment]
Problem solved in `uglify-es`. Make sure you have `3.3.9` version (`npm cache clear --force && npm install`). Also i recommending use `lock` files to avoid this problem in future. Thanks everyone!

**Comment by Slapbox** [comment]
I'm using `uglify-es 3.3.10` and having this issue. Is `3.3.10` broken?

**Comment by Slapbox** [comment]
Using 3.3.9 after clearing my `node_modules` and yarn's cache with `uglifyjs-webpack-plugin` fails with this same error.

**Comment by rayfoss** [comment]
uglify-es 3.3.10 is very very broken... thus projects with the best practice ^3.3.4 may brake. Good thing docker exists.
