### ISSUE TITLE
 Unhandled rejection TypeError: child.send is not a function

### ISSUE THREAD

**Issue by krrssna-g-s** [webpack-contrib/uglifyjs-webpack-plugin#254]
Hi,

I'm seeing below issue in my ubuntu box through Jenkins.  Any help appreciated.

 node[3708]: pthread_create: Resource temporarily unavailable
 Unhandled rejection TypeError: child.send is not a function
     at fork (/app/onejenkins/workspace/app.Build/build/node_modules/worker-farm/lib/fork.js:22:9)
     at Farm.startChild (/app/onejenkins/workspace/app.Build/build/node_modules/worker-farm/lib/farm.js:106:16)
     at Farm.processQueue (/app/onejenkins/workspace/app.Build/build/node_modules/worker-farm/lib/farm.js:279:10)
     at Farm.addCall (/app/onejenkins/workspace/app.Build/build/node_modules/worker-farm/lib/farm.js:307:8)
     at Farm.<anonymous> (/app/onejenkins/workspace/app.Build/build/node_modules/worker-farm/lib/farm.js:38:10)
     at _class.boundWorkers (/app/onejenkins/workspace/app.Build/build/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
     at enqueue (/app/onejenkins/workspace/app.Build/build/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
     at tryCatcher (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/promise.js:689:18)
     at Async._drainQueue (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/async.js:133:16)
     at Async._drainQueues (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/async.js:143:10)
     at Immediate.Async.drainQueues (/app/onejenkins/workspace/app.Build/build/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:789:20)
     at tryOnImmediate (timers.js:751:5)
     at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by evilebottnawi** [comment]
@krrssna-g-s strange error, can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
@krrssna-g-s friendly ping

**Comment by evilebottnawi** [comment]
@krrssna-g-s seems problem in you box, node can't create new thread - `node[3708]: pthread_create: Resource temporarily unavailable`. Maybe you have some limits in your box. If problem still exists please create issue https://github.com/nodejs/node. Thanks!

**Comment by ryantando** [comment]
@krrssna-g-s have you solved it? I have the same problem
