### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by Capybarab** [webpack-contrib/uglifyjs-webpack-plugin#28]
module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack/lib/RequestShortener'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/HAL/Lab/lab/progressive/node_modules/uglifyjs-webpack-plugin/dist/index.js:17:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

I ran: 
yarn add uglifyjs-webpack-plugin --dev ( version     "uglifyjs-webpack-plugin": "^0.4.3")

**Comment by bebraw** [comment]
Which version of webpack are you using?

**Comment by Capybarab** [comment]
Latest. It was a problem of webpack new format version rather than uglify. Apologise for not reporting it early. 

Regards,

**Comment by bebraw** [comment]
> Latest. It was a problem of webpack new format version rather than uglify. My apologies for not reporting it early.

Ok, so it has been fixed already in the core?

**Comment by michael-ciniawsky** [comment]
Reopen if still regressions, but seems to be resolved

**Comment by mbrevda** [comment]
Just came across this. It seems node isn't resolving the path to the dep correct.

In my case, I have a package with all my build tools, including webpack. Instead of being fully flattened, webpack is being installed a dep of my build tools package (not sure where it's supposed to go).
