### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by believer-ufa** [webpack-contrib/uglifyjs-webpack-plugin#299]
Hello!

We are trying to compress our code through latest version of your plugin (1.2.5) and getting following error message on compressing one of our chunks:

```
ERROR in 0.build.8700bad784a90189b741.js from UglifyJs
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at AST_Dot.eval [as _eval] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:9960:67)
    at AST_Dot.eval [as evaluate] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:9761:28)
    at eval (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:13531:23)
    at AST_Dot.eval [as optimize] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7677:23)
    at Compressor.before (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7660:24)
    at AST_Dot.eval [as transform] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4687:43)
    at Compressor.before (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7655:9)
    at AST_Call.eval [as transform] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4718:33)
    at Compressor.before (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7655:9)
    at AST_Binary.eval [as transform] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4629:49)
    at Compressor.before (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7655:9)
    at AST_Return.eval [as transform] (eval at <anonymous> (/home/roman/www/rawg-web/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
```

Please can you explain what a problem in that? Other chunks, as i see, compressed successfully.

And even that chunk compressing fine if i run `uglifyjs 0.build.8700bad784a90189b741.js > text.js` from my command line.

**Comment by evilebottnawi** [comment]
@believer-ufa please create minimum reproducible test repo, webpack can modify some code, need ivnestigate, but looks problem in `uglify`

**Comment by believer-ufa** [comment]
Problem appears on using `unsafe` compress option turned on. Sorry for anxiety, yes, i think that problem inside `uglify-es`.
