### ISSUE TITLE
 node-sass@4.9.0 install C:\xampp\htdocs\mark\node_modules\node-sass > node scripts/install.js

### ISSUE THREAD

**Issue by ramiasg** [webpack-contrib/uglifyjs-webpack-plugin#300]
> node-sass@4.9.0 install C:\xampp\htdocs\mark\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\fauzia hariri\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\xampp\htdocs\mark\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.9.0 postinstall C:\xampp\htdocs\mark\node_modules\node-sass
> node scripts/build.js

Binary found at C:\xampp\htdocs\mark\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall C:\xampp\htdocs\mark\node_modules\gifsicle
> node lib/install.js

  ‼ getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443
  ‼ gifsicle pre-build test failed
  i compiling from source
  × RequestError: getaddrinfo ENOTFOUND github.com github.com:443
    at ClientRequest.<anonymous> (C:\xampp\htdocs\mark\node_modules\got\index.js:74:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

> mozjpeg@5.0.0 postinstall C:\xampp\htdocs\mark\node_modules\mozjpeg
> node lib/install.js

**Comment by evilebottnawi** [comment]
>  getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443

You don't have access to github
