### ISSUE TITLE
Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by KokoTa** [webpack-contrib/uglifyjs-webpack-plugin#31]
```
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'reset' of undefined
    at F:\Github\Program\My-test\Webpack\www2\node_modules\_uglifyjs-webpack-plugin@0.4.3@uglifyjs-webpack-plugin\dist\index.js:99:22
    at F:\Github\Program\My-test\Webpack\www2\node_modules\_uglifyjs-webpack-plugin@0.4.3@uglifyjs-webpack-plugin\dist\index.js:231:9
    at Array.forEach (native)
    at Compilation.<anonymous> (F:\Github\Program\My-test\Webpack\www2\node_modules\_uglifyjs-webpack-plugin@0.4.3@uglifyjs-webpack-plugin\dist\index.js:54:19)
    at Compilation.applyPluginsAsyncSeries (F:\Github\Program\My-test\Webpack\www2\node_modules\_tapable@0.2.6@tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\Compilation.js:635:10)
    at next (F:\Github\Program\My-test\Webpack\www2\node_modules\_tapable@0.2.6@tapable\lib\Tapable.js:138:11)
    at Compilation.compilation.plugin.callback (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\ProgressPlugin.js:113:6)
    at Compilation.applyPluginsAsyncSeries (F:\Github\Program\My-test\Webpack\www2\node_modules\_tapable@0.2.6@tapable\lib\Tapable.js:142:13)
    at sealPart2 (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\Compilation.js:631:9)
    at next (F:\Github\Program\My-test\Webpack\www2\node_modules\_tapable@0.2.6@tapable\lib\Tapable.js:138:11)
    at Compilation.compilation.plugin (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\ProgressPlugin.js:109:6)
    at Compilation.applyPluginsAsyncSeries (F:\Github\Program\My-test\Webpack\www2\node_modules\_tapable@0.2.6@tapable\lib\Tapable.js:142:13)
    at Compilation.seal (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\Compilation.js:579:8)
    at F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\Compiler.js:493:16
    at F:\Github\Program\My-test\Webpack\www2\node_modules\_tapable@0.2.6@tapable\lib\Tapable.js:225:11
    at _addModuleChain (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (F:\Github\Program\My-test\Webpack\www2\node_modules\_webpack@2.5.1@webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

What's 'reset' mean?

**Comment by bebraw** [comment]
Impossible to say. There's not enough information to debug.

**Comment by orlv** [comment]
UglifyJS v3 has a new, backwards incompatible API. I guess it has no methods like uglify.base54.reset() or uglify.parse()

**Comment by bebraw** [comment]
Ah, you are using Uglify 3... The plugin doesn't support Uglify 3 yet.

**Comment by KokoTa** [comment]
Thanks! I changed v2.8.23 and it can work:)

**Comment by bebraw** [comment]
Ok, track #32 for progress with UglifyJS 3. I expect that will be a new major version of the plugin as the API it provides has to change as well most likely.

**Comment by kwelch** [comment]
**Question**
I am seeing this when using Uglify from `webpack.optimize.UglifyJsPlugin` in `webpack@3.4.1` is there something I should be doing in particular?

**Comment by kwelch** [comment]
@bebraw I am still having this issue. Should we re-open this ticket or create a new one? You should be able to use my repo from my previous comment to reproduce the error message. 
I have [created a branch](https://github.com/kwelch/simple-react-starter/tree/uglifyjs-31) to ensure master does no update prior to you getting a chance to look at this.

**Comment by michael-ciniawsky** [comment]
@kwelch Try the `beta` which supports `uglify-es` && parallelization `npm i -D uglifyjs-webpack-plugin@beta`

**Comment by kwelch** [comment]
@michael-ciniawsky 
I pushed a [new branch](https://github.com/kwelch/simple-react-starter/tree/uglifyjs-31-beta) that has a direct dependency on the beta version of the plugin and was presented with a new error. 

Error:
```
ERROR in main.d7ce55c1ec45ae99acd0.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:20:19)
    at /Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:75:21
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:54:20)
    at next (/Users/welchk/_git/oss/simple-react-starter/node_modules/tapable/lib/Tapable.js:186:14)
    at /Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/index.js:225:13
    at step (/Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:110:11)
    at done (/Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:120:22)
    at /Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:125:15
    at _class.worker (/Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:78:13)
    at enqueue (/Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:117:18)
    at /Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:134:11
    at Array.forEach (native)
    at _class.runTasks (/Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:114:13)
    at Compilation.<anonymous> (/Users/welchk/_git/oss/simple-react-starter/node_modules/uglifyjs-webpack-plugin/dist/index.js:151:18)
    at Compilation.applyPluginsAsyncSeries (/Users/welchk/_git/oss/simple-react-starter/node_modules/tapable/lib/Tapable.js:188:13)
    at self.applyPluginsAsync.err (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/lib/Compilation.js:640:10)
    at Compilation.applyPluginsAsyncSeries (/Users/welchk/_git/oss/simple-react-starter/node_modules/tapable/lib/Tapable.js:177:46)
    at sealPart2 (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/lib/Compilation.js:636:9)
    at Compilation.applyPluginsAsyncSeries (/Users/welchk/_git/oss/simple-react-starter/node_modules/tapable/lib/Tapable.js:177:46)
    at Compilation.seal (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/lib/Compilation.js:579:8)
    at applyPluginsParallel.err (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/lib/Compiler.js:514:17)
    at /Users/welchk/_git/oss/simple-react-starter/node_modules/tapable/lib/Tapable.js:271:11
    at _addModuleChain (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/welchk/_git/oss/simple-react-starter/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by michael-ciniawsky** [comment]
Try without `devtool` especially `cheap-source-maps` don't work with this plugin

**Comment by kwelch** [comment]
Good to know thanks!

**Comment by kwelch** [comment]
@michael-ciniawsky I took out all settings about related to devtool and still same `reset` error.

**Comment by alejuanito** [comment]
You must install uglify2 
npm i uglify-js@2 -D
