### ISSUE TITLE
sourceMaps.sections

### ISSUE THREAD

**Issue by ramnycordero** [webpack-contrib/uglifyjs-webpack-plugin#330]
92% chunk asset optimization/home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:20
  return sourceMap.sections != null
                   ^

TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (.../node_modules/uglifyjs-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:20:20)
    at UglifyJsPlugin.buildError (/home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/dist/index.js:116:23)
    at /home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/dist/index.js:275:45
    at Array.forEach (<anonymous>)
    at /home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/dist/index.js:259:19
    at step (/home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at /home/android/www/bruno-mobile/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
    at /home/android/www/bruno-mobile/node_modules/worker-farm/lib/farm.js:191:19
    at process._tickCallback (internal/process/next_tick.js:61:11)
``

**Comment by evilebottnawi** [comment]
@ramnycordero Can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Looks you have broken source map

**Comment by ramnycordero** [comment]
I believe it's a trouble of npm, this me have happen rarely.

**Comment by evilebottnawi** [comment]
@ramnycordero without minimum reproducible test repo i can't help
