### ISSUE TITLE
TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by DMShamonov** [webpack-contrib/uglifyjs-webpack-plugin#360]
* Operating System: MacOS
* Node Version: 10.10.0
* NPM Version: 6.4.1
* webpack Version: 3.12.0
* ${package} Version: 2.0.1

### Actual Behavior

```
/.../node_modules/webpack-dev-server/bin/webpack-dev-server.js:373
    throw e;
    ^

TypeError: Cannot read property 'compilation' of undefined
    at UglifyJsPlugin.apply (/.../node_modules/uglifyjs-webpack-plugin/dist/index.js:321:20)
    at Compiler.apply (/.../node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/.../node_modules/webpack/lib/webpack.js:33:19)
    at startDevServer (/.../node_modules/webpack-dev-server/bin/webpack-dev-server.js:367:16)
    at portfinder.getPort (/.../node_modules/webpack-dev-server/bin/webpack-dev-server.js:358:5)
    at /.../node_modules/portfinder/lib/portfinder.js:190:16
    at /.../node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /.../node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /.../node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /.../node_modules/portfinder/lib/portfinder.js:151:16
    at Server.onListen (/.../node_modules/portfinder/lib/portfinder.js:43:7)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1320:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
error Command failed with exit code 1.
```

### Code

```
new UglifyjsWebpackPlugin({
        parallel: true,
        uglifyOptions: {
          compress: {
            drop_console: true,
          },
        },
      }),
```

**Comment by evilebottnawi** [comment]
@DMShamonov can you create minimum reproducible test repo, looks you use global installed webpack@3 version

**Comment by DMShamonov** [comment]
@evilebottnawi it's not global installed webpack. When I remove `UglifyjsWebpackPlugin` section from config it works without errors. 

I try reproducible test repo later.

**Comment by evilebottnawi** [comment]
@DMShamonov and you you use `minification` when you use `dev` server? It is only decrease compilation time

**Comment by DMShamonov** [comment]
@evilebottnawi it's `prod:test` build. For develop we use `dev` config without `UglifyjsWebpackPlugin `. But in `prod` config without `webpack-dev-server` we have the same error:
```
/.../node_modules/webpack/bin/webpack.js:348
                        throw err;
                        ^

TypeError: Cannot read property 'compilation' of undefined
    at UglifyJsPlugin.apply (/.../node_modules/uglifyjs-webpack-plugin/dist/index.js:321:20)
    at Compiler.apply (/.../node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/.../node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/.../node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/.../node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/.../node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/.../node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
error Command failed with exit code 1.
```

**Comment by evilebottnawi** [comment]
@DMShamonov without minimum reporudiclbe test repo i can't help, looks other plugin broke you webpack

**Comment by DMShamonov** [comment]
@evilebottnawi that's test repo [link](https://github.com/DMShamonov/uglifyjs-webpack-plugin-360-issue-reproducing)

**Comment by evilebottnawi** [comment]
@DMShamonov you use `webpack@3`, 2 version require `webpack@4`

**Comment by DMShamonov** [comment]
@evilebottnawi OMG... Ok, thanks!

**Comment by moronghui** [comment]
webpack@3 requires uglifyjs-webpack-plugin@1
