### ISSUE TITLE
Unexpected token: name ($parentLi)

### ISSUE THREAD

**Issue by Falseee** [webpack-contrib/uglifyjs-webpack-plugin#392]
Hello,

i use webpack the first time.
So i added the uglifyjs-webpack-plugin as plugin and tried to run webpack but i get the following error message:
```
ERROR in app.js from UglifyJs
Unexpected token: name ($parentLi) [./js/module/sidebar.js:3,0][app.js:98,12]
error Command failed with exit code 2.
```
If i run webpack in production mode i got error message
```
ERROR in app.js from UglifyJs
Unexpected token: name ($parentLi) [./js/module/sidebar.js:3,0][app.js:101,12]

ERROR in app.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/home/pc/git/admin-theme/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at module.exports (/home/pc/git/admin-theme/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (/home/pc/git/admin-theme/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/home/pc/git/admin-theme/node_modules/worker-farm/lib/child/index.js:51:3)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 2.
```

I use raw Javascript, so no Typescript or other stuff.

The Javascript file of the error message:
```
$(function () {
    $('ul.at-nav-item > li.at-hasmenu > a').click(function () {
        let $parentLi = $(this).parent('li');
        let $submenu = $parentLi.find('ul.at-nav-submenu');

        if ($parentLi.hasClass('at-nav-active')) {
            $parentLi.addClass('at-nav-close-animation');
            $submenu.slideUp(function () {
                $parentLi.removeClass('at-nav-active');
                $parentLi.removeClass('at-nav-close-animation');
            });
        } else {
            $parentLi.addClass('at-nav-active');
            $submenu.slideDown();
        }
    })
});
```

My Webpack config:
```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
module.exports = {
    mode: 'development',
    entry: [
        './js/module/sidebar.js',
        './js/module/topbar.js'
    ],
    output: {
        path: `${__dirname}/js/dist`,
        filename: 'app.js'
    },
    plugins: [
        new UglifyJSPlugin({
            sourceMap: true
        })
    ],
    devtool: 'source-map'
};
```

My package.json
```
{
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1"
  },
  "devDependencies": {
    "terser-webpack-plugin": "^1.2.1",
    "uglifyjs-webpack-plugin": "^2.1.1",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1"
  }
}
```

**Comment by evilebottnawi** [comment]
Not right repo, it is not terser repo
