### ISSUE TITLE
DefaultsError: `warnings` is not a supported option

### ISSUE THREAD

**Issue by kobe990** [webpack-contrib/uglifyjs-webpack-plugin#400]
* Operating System: Mac OS
* Node Version: 10.15.0
* NPM Version: 6.4.1
* webpack Version: 4.30.0
* uglifyjs-webpack-plugin Version: 2.1.2

### Expected Behavior

webpack can build the js correctly

### Actual Behavior

report a error:
DefaultsError: `warnings` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglify-js@3.5.10@uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at Function.buildError (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/index.js:103:54)
    at results.forEach (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/index.js:256:52)
    at Array.forEach (<anonymous>)
    at taskRunner.run (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/index.js:231:17)
    at step (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:83:9)
    at done (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:94:30)
    at boundWorkers (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:99:13)
    at TaskRunner.boundWorkers (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:68:11)
    at enqueue (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:89:14)
    at tasks.forEach (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:109:9)
    at Array.forEach (<anonymous>)
    at TaskRunner.run (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/TaskRunner.js:87:11)
    at UglifyJsPlugin.optimizeFn (/Users/zxa/IdeaProjects/lzdtp/node_modules/_uglifyjs-webpack-plugin@2.1.2@uglifyjs-webpack-plugin/dist/index.js:225:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/zxa/IdeaProjects/lzdtp/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/zxa/IdeaProjects/lzdtp/node_modules/_tapable@1.1.3@tapable/lib/Hook.js:154:20)

### Code

```js
  // webpack.config.js
 optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          compress: {
            warnings: false
          },
        },
        sourceMap: true
      }),
      new OptimizeCSSPlugin({
        cssProcessorOptions: {
          safe: true
        }
      })
    ],
```

### Description
* about 20 days ago, all things are right. today when I update my local node_modules, the error happened! I find the warning option is ok in the uglifyjs document. But now it doesn't work. I think some update on the webpack or some module lead to this error.

**Comment by kobe990** [comment]
compress option doesn't consist of warning option in fact. But I don't know why it could pass build before.

**Comment by jeoy** [comment]
Some package released new version a few day, I still haven't found which one is

**Comment by infolock** [comment]
FWIW, i've seen this issue when using the `terser-webpack-plugin` - reverting it appears to be the winner for me.

**Comment by kejiacheng** [comment]
> compress option doesn't consist of warning option in fact. But I don't know why it could pass build before

hello！ Have you solved the problem？

**Comment by kumaresan-subramani** [comment]
Hi I am also facing this error in my source recently.

one week before it works fine.

In local it is working fine  - **uglifyjs-webpack-plugin@2.1.2**

But while running in jenkins it throws below error:

> ERROR in vendors.bundle.js from UglifyJs
DefaultsError: `warnings` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/jenkins/workspace/grid-angular-samples_master-KGZGHS6RTY6XLQXUQWQ55ECXCFTEAMXT7SLUT7R6DKIUWVH6ZW4Q/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at Function.buildError (/jenkins/workspace/grid-angular-samples_master-KGZGHS6RTY6XLQXUQWQ55ECXCFTEAMXT7SLUT7R6DKIUWVH6ZW4Q/node_modules/uglifyjs-webpack-plugin/dist/index.js:103:54)
    at results.forEach (/jenkins/workspace/grid-angular-samples_master-KGZGHS6RTY6XLQXUQWQ55ECXCFTEAMXT7SLUT7R6DKIUWVH6ZW4Q/node_modules/uglifyjs-webpack-plugin/dist/index.js:256:52)
    at Array.forEach (<anonymous>)


**PLease provide any solution for me, this breaks my app**

**Comment by kumaresan-subramani** [comment]
THis not a problem with uglifyjs plugin, due to webpack-cli latest update this issue occurs

https://github.com/webpack/webpack-cli/issues/881

**Comment by jeoy** [comment]
hi, @kejiacheng , @kobe990  , it seems caused by upgrade of Uglify-js,

check this https://stackoverflow.com/a/55998303/10139109

**Comment by kejiacheng** [comment]
> hi, @kejiacheng , @kobe990 , it seems caused by upgrade of Uglify-js,
> 
> check this https://stackoverflow.com/a/55998303/10139109

thanks

**Comment by NelsonHereveri** [comment]
> THis not a problem with uglifyjs plugin, due to webpack-cli latest update this issue occurs
> 
> [webpack/webpack-cli#881](https://github.com/webpack/webpack-cli/issues/881)
It has worked as expected.

**Comment by tomorrowbye** [comment]
> compress option doesn't consist of warning option in fact. But I don't know why it could pass build before.

Hi! Have you solved the problem?
